name = input("Enter name : ")
last_name = input("Enter last name : ")
age = input("Enter age : ")
country = input("Enter country : ")
city = input("Enter city : ")
favorite_car = input("Enter favorite car : ")
favorite_color=input("Enter favorite color : ")
print("my name is " + name + " and my last name is " + last_name + " .i'm from " + country + " and my city is " + city +" im " + age + "years old" + "my favourite car is " + favorite_car + " my favorite color is " + favorite_color)

x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)

x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)

x = int(input())
y = int(input())
print(x / y)
x = int(input())
y = int(input())
print(x / y)
x = int(input())
y = int(input())
print(x / y)
x = int(input())
y = int(input())
print(x / y)
x = int(input())
y = int(input())
print(x / y)