name = input("Enter name : ")
last_name = input("Enter last name : ")
age = int(input("Enter age : "))
country = input("Enter country : ")
city = input("Enter city : ")
favorite_car = input("Enter favorite car : ")
favorite_color=input("Enter favorite color : ")
print("Hello my name is " + name + " and my last name is " + last_name + " .i'm from " + country + " i live at " + city +" im " + str(age) + "years old" + "my favourite car is " + favorite_car + " my favorite color is " + favorite_color)

x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)
x = int(input())
y = int(input())
print(x + y)

x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)
x = int(input())
y = int(input())
print(x - y)

x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)
x = int(input())
y = int(input())
print(x * y)

x = int(input())
y = int(input())
print(x // y)
x = int(input())
y = int(input())
print(x // y)
x = int(input())
y = int(input())
print(x // y)
x = int(input())
y = int(input())
print(x // y)
x = int(input())
y = int(input())
print(x // y)
x = int(input())
y = int(input())
print(x // y)
x = int(input())
y = int(input())
print(x // y)
x = int(input())
y = int(input())
print(x // y)
x = int(input())
y = int(input())
print(x // y)
x = int(input())
y = int(input())
print(x // y)



#int() - დახმარებით ჩვენ გადაგვყავს string integer - ად მაგრამ ეს მხოლოდ ხდება როდესაც string არის ციფრი
#str() - დახმარებით ჩვენ გადაგვყავს integer ან float - string - ში 
#type() - ის დახმარებით ჩვენ შეგვიძლია გავიგოთ რომელიმე ცვლადი str - არის  int - aris თუ float - არის
#input() - ის საშვალებით ჩვენ გვეძლევა შესაძლებლობა რომ შავიყვანოთ რაიმე მაგალითი